### ISSUE TITLE
Grammatical Bugs?

### ISSUE THREAD

**Issue by hejjoe** [ungeschneuer/plenum_first_said#4]
Some of the words of https://mastodon.social/@bt_first_said were quite familiar to me. So I looked up, if the BTFS-algorithm was right. Here are some examples, where the algorithm might have failed, so the algorithm can be improved. Most of the examples are related to grammatical variations.

1. 
"#Wasserstoffelektrolyseur tauchte zum ersten Mal im Protokoll der 34. Sitzung des 20. Deutschen Bundestages am 12.05.2022 auf. Das Protokoll findet man unter https://dserver.bundestag.de/btp/20/20034.pdf"
https://mastodon.social/@FSBT_Kontext/108366476454370056

"Dieser Strom muss natürlich ersetzt werden. Genau an dieser Stelle soll, wenn es nach uns geht, einer der größten Wasserstoffelektrolyseure Europas entstehen."
https://dserver.bundestag.de/btp/19/19233.pdf#page=49

2. 
"#Planungshemmnisse tauchte zum ersten Mal im Protokoll der 34. Sitzung des 20. Deutschen Bundestages am 12.05.2022 auf. Das Protokoll findet man unter https://dserver.bundestag.de/btp/20/20034.pdf"
https://mastodon.social/@FSBT_Kontext/108368462167136096

"Wer Bürgerbeteiligung nur als ein Planungshemmnis, als ein Erschwernis für Investoren ansieht und nicht bereit ist, für Stadtentwicklung die Chance einer Akzeptanz der Bürger zu nutzen, der muß davon ausgehen, daß sich die Kritiker und Widerstrebenden nicht mehr in den Amtsstuben oder Parlamentsräumen unserer Städte, sondern im Gerichtssaal mit dem auseinandersetzen, was dann in einzelnen Gemeinden beschlossen wurde."
https://dserver.bundestag.de/btp/10/10241.pdf#page=56

3. 
"#Ressourceninteressen tauchte zum ersten Mal im Protokoll der 37. Sitzung des 20. Deutschen Bundestages am 19.05.2022 auf. Das Protokoll findet man unter https://dserver.bundestag.de/btp/20/20037.pdf"
https://mastodon.social/@FSBT_Kontext/108369067589368094

"Wir haben in Deutschland eine gute Tradition der Polarforschung und exzellente Wissenschaftler. Diese muss weiter gestärkt werden, und allein daraus ergibt sich auch schon die Verantwortung, eine Arktispolitik zu verfolgen, die sich nicht von Handels- und Ressourceninteressen leiten lässt, sondern den Umwelt- und Klimaschutz in den Mittelpunkt stellt."
https://dserver.bundestag.de/btp/17/17126.pdf#page=154

4.
"#Sicherheitsgleichgewicht tauchte zum ersten Mal im Protokoll der 37. Sitzung des 20. Deutschen Bundestages am 19.05.2022 auf. Das Protokoll findet man unter https://dserver.bundestag.de/btp/20/20037.pdf"
https://mastodon.social/@FSBT_Kontext/108389931767263804

"Durch die Bundeswehr tragen wir in vertrauensvoller Zusammenarbeit mit unseren amerikanischen Freunden und mit unseren übrigen Verbündeten zur Bewahrung des globalen, des weltweiten Sicherheitsgleichgewichts bei und erhalten damit die Voraussetzungen für die Politik der Entspannung."
https://dserver.bundestag.de/btp/07/07235.pdf#page=10

5.
"#Ledger tauchte zum ersten Mal im Protokoll der 30. Sitzung des 20. Deutschen Bundestages am 27.04.2022 auf. Das Protokoll findet man unter https://dserver.bundestag.de/btp/20/20030.pdf"
https://mastodon.social/@FSBT_Kontext/108391311846767229

"Ich bin kein Jurist, sondern Mathematiker, und kenne deshalb die kryptografischen Verfahren, die hinter der Distributed-Ledger-Technologie – das ist der Oberbegriff von Blockchain-Technologien – stecken, sehr genau."
https://dserver.bundestag.de/btp/19/19215.pdf#page=138

6.
"#Gefühlspolitikern tauchte zum ersten Mal im Protokoll der 37. Sitzung des 20. Deutschen Bundestages am 19.05.2022 auf. Das Protokoll findet man unter https://dserver.bundestag.de/btp/20/20037.pdf"
https://mastodon.social/@FSBT_Kontext/108392381360567693

"Ich fürchte, daß man diesen Unterschied bei der Debatte nicht immer gemacht hat. Ist es nicht z. B. Gefühlspolitik, wenn man durch Verharmlosung der Weltgefahren Beruhigungspillen verabfolgt?"
https://dserver.bundestag.de/btp/01/01191.pdf#page=16

7.
"#Systemumbrüchen tauchte zum ersten Mal im Protokoll der 36. Sitzung des 20. Deutschen Bundestages am 18.05.2022 auf. Das Protokoll findet man unter https://dserver.bundestag.de/btp/20/20036.pdf"
https://mastodon.social/@FSBT_Kontext/108396183917838301

"Es stellte sich doch für uns alle die Frage: Sind dies alles Mängel des gegliederten Systems, die innerhalb des Systems überwunden werden können, oder können sie nur durch Systemumbruch überwunden werden, sprich: durch die integrierte Gesamtschule?"
https://dserver.bundestag.de/btp/08/08193.pdf#page=77

8.
"#Handelszentren tauchte zum ersten Mal im Protokoll der 36. Sitzung des 20. Deutschen Bundestages am 18.05.2022 auf. Das Protokoll findet man unter https://dserver.bundestag.de/btp/20/20036.pdf"
https://mastodon.social/@FSBT_Kontext/108417897147001490

"Ist sich die Bundesregierung dessen bewußt, daß die angestrebte TEE-Verbindung zahlreiche Großstädte in Frankreich und in der Bundesrepublik verbinden und bedeutende Industrie- und Handelszentren berühren würde und somit eine große wirtschaftliche Bedeutung hätte und insbesondere zu Zeiten, da infolge der Witterungsverhältnisse der Flugverkehr erschwert wird, von besonderer Wichtigkeit wäre?"
https://dserver.bundestag.de/btp/04/04192.pdf#page=17

9.
"#Kulturbudget tauchte zum ersten Mal im Protokoll der 41. Sitzung des 20. Deutschen Bundestages am 02.06.2022 auf. Das Protokoll findet man unter https://dserver.bundestag.de/btp/20/20041.pdf"
https://mastodon.social/@FSBT_Kontext/108419348097601314

"Die 113 Einrichtungen mit ihren rund 70 000 Schülern und über 1 500 aus Deutschland entsandten Lehrern verschlingen ein Drittel des Kulturbudgets des Auswärtigen Amtes."
https://dserver.bundestag.de/btp/13/13110.pdf#page=24

10.
"#Weizenfeldern tauchte zum ersten Mal im Protokoll der 33. Sitzung des 20. Deutschen Bundestages am 11.05.2022 auf. Das Protokoll findet man unter https://dserver.bundestag.de/btp/20/20033.pdf"
https://mastodon.social/@FSBT_Kontext/108349799988135602

"Mancher, der diesen Gesetzentwurf trägt und unterstützt, denkt wohl eher an ausgeräumte Landschaften, an kilometer-
lange Mais- oder Weizenfelder, an Großbetriebe in der Viehhaltung, an maximalen Düngerverbrauch und starken Einsatz von Pflanzenschutzmitteln."
https://dserver.bundestag.de/btp/10/10123.pdf#page=29

**Comment by ungeschneuer** [comment]
Bei 1, 3, 4, 8, 9 und 10 war es wahrscheinlich ein Problem mit dem Bindestrich. Das steht auf der Liste, aber konnte ich bisher nicht klug lösen. 
Für 2 wurde eine Regel implementiert. 
Zu 5: Ja, Ledger taucht in einem zusammengesetzen Wort schon auf, jedoch würde ich das als separates Wort gelten lassen. 
Zu 6: Das soll eigentlich so. Politik und Politiker sind ja auch verschiedene Dinge.
Zu 7: Uff, ja, Plural mit Umlaut habe ich bisher nicht gemeistert. Habe mit Wortstämmen experimentiert, funktioniert bei Neologismus aber auch nicht wirklich.

**Comment by ungeschneuer** [comment]
I tried to solve some aspects with #8 that should solve most of the mentioned problems combined with the additional match processing via OPTV.
